name: invoice_kit
description: "Production-ready Flutter boilerplate — Clean Architecture, BLoC, GetIt, GoRouter."
publish_to: "none"
version: 1.0.0+1

environment:
   sdk: ^3.12.0
   flutter: ">=3.24.0"

dependencies:
   flutter:
      sdk: flutter
   flutter_localizations:
      sdk: flutter

   # UI / Icons
   cupertino_icons: ^1.0.8
   flutter_svg: ^2.0.10+1
   cached_network_image: ^3.3.1
   lottie: ^3.1.0
   shimmer: ^3.0.0
   gap: ^3.0.1

   # State Management
   flutter_bloc: ^9.1.1
   bloc: ^9.2.1
   equatable: ^2.0.5

   # Dependency Injection
   get_it: ^9.2.1
   injectable: ^3.0.0

   # Networking
   dio: ^5.7.0
   http: ^1.2.2

   # Routing
   go_router: ^17.3.0

   # Local Storage
   shared_preferences: ^2.3.2
   flutter_secure_storage: ^10.3.1
   hive: ^2.2.3
   hive_flutter: ^1.1.0

   # Environment / Config
   flutter_dotenv: ^6.0.1

   # Serialization
   json_annotation: ^4.9.0

   # Logging
   logger: ^2.4.0

   # Localization
   intl: ^0.20.2

   # Utilities─
   connectivity_plus: ^7.1.1
   package_info_plus: ^10.1.0
   device_info_plus: ^13.1.0
   permission_handler: ^12.0.3

   # Misc
   url_launcher: ^6.3.0
   path_provider: ^2.1.4

   # PDF & Sharing (InvoiceKit)
   pdf: ^3.11.1
   printing: ^5.13.3
   share_plus: ^13.0.0

   # Charts (Reports)
   fl_chart: ^1.2.0

   # File picking / image
   image_picker: ^1.1.2
   file_picker: ^12.0.0-beta.7
   hugeicons_pro: ^0.0.3
   supabase_flutter: ^2.15.0

dev_dependencies:
   flutter_test:
      sdk: flutter
   bloc_test: ^10.0.0
   mocktail: ^1.0.4

   # Code generation
   build_runner: ^2.4.13

   # Linting
   flutter_lints: ^6.0.0
   very_good_analysis: ^10.2.0

flutter:
   uses-material-design: true
   generate: true

   # Assets
   assets:
      - assets/images/
      - assets/icons/
      - assets/svgs/
      - assets/lottie/
      - assets/translations/
      - assets/mock/
      - .env

   # Fonts
   fonts:
      - family: DMSans
        fonts:
           - asset: assets/fonts/DMSans-Regular.ttf
           - asset: assets/fonts/DMSans-Medium.ttf
      - family: Oswald
        fonts:
           - asset: assets/fonts/Oswald-Bold.ttf
           - asset: assets/fonts/Oswald-SemiBold.ttf
      - family: SpaceGrotesk
        fonts:
           - asset: assets/fonts/SpaceGrotesk-Bold.ttf
           - asset: assets/fonts/SpaceGrotesk-SemiBold.ttf
