import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:hugeicons_pro/hugeicons.dart';
import 'package:invoice_kit/core/extensions/context_extensions.dart';
import 'package:invoice_kit/core/theme/app_spacing.dart';
import 'package:invoice_kit/core/utils/formatters.dart';
import 'package:invoice_kit/core/widgets/widgets.dart';
import 'package:invoice_kit/features/clients/presentation/bloc/clients_cubit.dart';
import 'package:invoice_kit/features/recurring/domain/entities/recurring_invoice.dart';
import 'package:invoice_kit/features/recurring/presentation/bloc/recurring_cubit.dart';

class RecurringScreen extends StatefulWidget {
  const RecurringScreen({super.key});

  @override
  State<RecurringScreen> createState() => _RecurringScreenState();
}

class _RecurringScreenState extends State<RecurringScreen> {
  @override
  void initState() {
    super.initState();
    context.read<RecurringCubit>().load();
    context.read<ClientsCubit>().load();
  }

  Future<void> _runDue() async {
    final cubit = context.read<RecurringCubit>();
    final count = await cubit.runDue();
    if (!mounted) return;
    context.showSnackBar(
      'Generated $count invoice${count == 1 ? '' : 's'}',
    );
  }

  Future<void> _confirmDelete(RecurringInvoice s) async {
    final ok = await showDialog<bool>(
      context: context,
      builder: (dialogCtx) => AlertDialog(
        title: const Text('Delete schedule?'),
        content: const Text(
          'Existing invoices generated by this schedule will remain.',
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(dialogCtx, false),
            child: const Text('Cancel'),
          ),
          FilledButton.tonal(
            onPressed: () => Navigator.pop(dialogCtx, true),
            child: const Text('Delete'),
          ),
        ],
      ),
    );
    if (ok == true) {
      await context.read<RecurringCubit>().remove(s.id);
    }
  }

  @override
  Widget build(BuildContext context) {
    return AppScaffold(
      title: 'Recurring',
      actions: [
        IconButton(
          icon: const Icon(HugeIconsStroke.flag01, size: 18),
          tooltip: 'Run due now',
          onPressed: _runDue,
        ),
      ],
      refreshable: true,
      onRefresh: () => context.read<RecurringCubit>().load(),
      body: BlocBuilder<RecurringCubit, RecurringState>(
        builder: (context, state) {
          if (state.loading && state.schedules.isEmpty) {
            return ListView(
              children: const [
                SizedBox(height: 120),
                Center(child: CircularProgressIndicator()),
              ],
            );
          }
          if (state.schedules.isEmpty) {
            return ListView(
              children: const [
                SizedBox(height: 32),
                EmptyState(
                  icon: Icons.repeat_rounded,
                  title: 'No recurring schedules',
                  subtitle: 'Set a schedule to auto-generate invoices on a daily, weekly, monthly, or yearly cadence.',
                ),
              ],
            );
          }
          return BlocBuilder<ClientsCubit, ClientsState>(
            builder: (context, cstate) {
              final byId = {for (final c in cstate.clients) c.id: c};
              return ListView.builder(
                padding: const EdgeInsets.fromLTRB(
                  AppSpacing.lg,
                  AppSpacing.md,
                  AppSpacing.lg,
                  AppSpacing.xxxl,
                ),
                itemCount: state.schedules.length,
                itemBuilder: (_, i) {
                  final s = state.schedules[i];
                  final client = byId[s.clientId];
                  return _ScheduleCard(
                    schedule: s,
                    clientName: client?.name,
                    onToggle: (v) async {
                      await context.read<RecurringCubit>().upsert(
                        s.copyWith(active: v),
                      );
                    },
                    onDelete: () => _confirmDelete(s),
                  );
                },
              );
            },
          );
        },
      ),
    );
  }
}

class _ScheduleCard extends StatelessWidget {
  const _ScheduleCard({
    required this.schedule,
    required this.clientName,
    required this.onToggle,
    required this.onDelete,
  });

  final RecurringInvoice schedule;
  final String? clientName;
  final ValueChanged<bool> onToggle;
  final VoidCallback onDelete;

  @override
  Widget build(BuildContext context) {
    final tt = context.textTheme;
    final muted = context.colors.onSurfaceVariant;
    return AppCard(
      margin: const EdgeInsets.symmetric(vertical: AppSpacing.xs),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      clientName ?? 'Unknown client',
                      style: tt.titleMedium?.copyWith(
                        fontWeight: FontWeight.w700,
                        letterSpacing: -0.1,
                      ),
                    ),
                    const SizedBox(height: 2),
                    Text(
                      '${schedule.frequency.label} · ${schedule.currency}',
                      style: tt.bodySmall?.copyWith(color: muted),
                    ),
                  ],
                ),
              ),
              Switch.adaptive(
                value: schedule.active,
                onChanged: onToggle,
              ),
            ],
          ),
          const SizedBox(height: AppSpacing.md),
          Row(
            children: [
              Icon(HugeIconsStroke.clock01, size: 16, color: muted),
              const SizedBox(width: AppSpacing.xs),
              Text(
                'Next run ${Formatters.date(schedule.nextRunDate)}',
                style: tt.bodySmall?.copyWith(color: muted),
              ),
            ],
          ),
          if (schedule.endDate != null) ...[
            const SizedBox(height: 4),
            Row(
              children: [
                Icon(HugeIconsStroke.calendar01, size: 16, color: muted),
                const SizedBox(width: AppSpacing.xs),
                Text(
                  'Ends ${Formatters.date(schedule.endDate!)}',
                  style: tt.bodySmall?.copyWith(color: muted),
                ),
              ],
            ),
          ],
          const SizedBox(height: AppSpacing.md),
          const Divider(height: 1),
          const SizedBox(height: AppSpacing.sm),
          Row(
            mainAxisAlignment: MainAxisAlignment.end,
            children: [
              TextButton.icon(
                onPressed: onDelete,
                icon: const Icon(HugeIconsStroke.delete01, size: 18),
                label: const Text('Delete'),
              ),
            ],
          ),
        ],
      ),
    );
  }
}
