import 'package:dio/dio.dart';
import 'package:flutter_boilerplate/app/app_config.dart';
import 'package:flutter_boilerplate/core/connectivity/connectivity_service.dart';
import 'package:flutter_boilerplate/core/errors/error_handler.dart';
import 'package:flutter_boilerplate/core/errors/error_mapper.dart';
import 'package:flutter_boilerplate/core/logger/logger.dart';
import 'package:flutter_boilerplate/core/network/dio_client.dart';
import 'package:flutter_boilerplate/core/network/http_api_client.dart';
import 'package:flutter_boilerplate/core/network/interceptors/auth_interceptor.dart';
import 'package:flutter_boilerplate/core/network/interceptors/logging_interceptor.dart';
import 'package:flutter_boilerplate/core/network/interceptors/refresh_token_interceptor.dart';
import 'package:flutter_boilerplate/core/permissions/permissions_service.dart';
import 'package:flutter_boilerplate/core/security/device_integrity_service.dart';
import 'package:flutter_boilerplate/core/storage/hive_storage_service.dart';
import 'package:flutter_boilerplate/core/storage/local_storage_service.dart';
import 'package:flutter_boilerplate/core/storage/secure_storage_service.dart';
import 'package:flutter_boilerplate/features/authentication/data/datasources/auth_local_datasource.dart';
import 'package:flutter_boilerplate/features/authentication/data/datasources/auth_remote_datasource.dart';
import 'package:flutter_boilerplate/features/authentication/data/repositories/auth_repository_impl.dart';
import 'package:flutter_boilerplate/features/authentication/domain/repositories/auth_repository.dart';
import 'package:flutter_boilerplate/features/authentication/domain/usecases/forgot_password_usecase.dart';
import 'package:flutter_boilerplate/features/authentication/domain/usecases/login_usecase.dart';
import 'package:flutter_boilerplate/features/authentication/domain/usecases/logout_usecase.dart';
import 'package:flutter_boilerplate/features/authentication/domain/usecases/register_usecase.dart';
import 'package:flutter_boilerplate/features/authentication/presentation/bloc/auth_bloc.dart';
import 'package:get_it/get_it.dart';

/// Global service locator.
final GetIt sl = GetIt.instance;

/// Programmatically registers dependencies.
///
/// If you prefer codegen, replace this with `@injectable` annotations and
/// `injection.config.dart` generated by build_runner.
Future<void> configureDependencies({
  required AppConfig config,
  required LocalStorageService localStorage,
}) async {
  // ── App-level singletons ───────────────────────────────────────────────
  sl
    ..registerSingleton<AppConfig>(config)
    ..registerSingleton<LocalStorageService>(localStorage)
    ..registerSingleton<SecureStorageService>(SecureStorageService())
    ..registerSingleton<HiveStorageService>(await HiveStorageService.initialize())
    ..registerSingleton<CoreLogger>(CoreLogger(enabled: config.enableLogging))
    ..registerSingleton<ConnectivityService>(ConnectivityService()..initialize())
    ..registerSingleton<PermissionsService>(const PermissionsService())
    ..registerSingleton<DeviceIntegrityService>(const DeviceIntegrityService())
    ..registerSingleton<HttpApiClient>(HttpApiClient())
    ..registerSingleton<ErrorMapper>(const DefaultErrorMapper())
    ..registerSingleton<ErrorHandler>(ErrorHandler(sl<ErrorMapper>()));

  // ── Dio stack ─────────────────────────────────────────────────────────
  final tokenProvider = SecureStorageTokenProvider(sl<SecureStorageService>());
  sl
    ..registerSingleton<TokenProvider>(tokenProvider)
    ..registerSingleton<AuthInterceptor>(
      AuthInterceptor(config: config, tokenProvider: tokenProvider),
    )
    ..registerSingleton<RefreshTokenInterceptor>(
      RefreshTokenInterceptor(
        secureStorage: sl<SecureStorageService>(),
        dio: Dio(BaseOptions(baseUrl: config.apiBaseUrl)),
      ),
    )
    ..registerSingleton<LoggingInterceptor>(
      LoggingInterceptor(logger: sl<CoreLogger>().raw, enabled: config.enableLogging),
    )
    ..registerSingleton<DioClient>(
      DioClient.create(
        config: config,
        authInterceptor: sl<AuthInterceptor>(),
        refreshTokenInterceptor: sl<RefreshTokenInterceptor>(),
        loggingInterceptor: sl<LoggingInterceptor>(),
      ),
    )
    ..registerSingleton<Dio>(sl<DioClient>().dio)
    // ── Authentication feature ─────────────────────────────────────────────
    ..registerSingleton<AuthRemoteDataSource>(AuthRemoteDataSourceImpl(sl<Dio>()))
    ..registerSingleton<AuthLocalDataSource>(
      AuthLocalDataSourceImpl(sl<SecureStorageService>(), sl<HiveStorageService>()),
    )
    ..registerSingleton<AuthRepository>(
      AuthRepositoryImpl(
        remote: sl<AuthRemoteDataSource>(),
        local: sl<AuthLocalDataSource>(),
        errorHandler: sl<ErrorHandler>(),
        tokenProvider: tokenProvider,
      ),
    )
    ..registerSingleton<LoginUseCase>(LoginUseCase(sl<AuthRepository>()))
    ..registerSingleton<RegisterUseCase>(RegisterUseCase(sl<AuthRepository>()))
    ..registerSingleton<LogoutUseCase>(LogoutUseCase(sl<AuthRepository>()))
    ..registerSingleton<ForgotPasswordUseCase>(ForgotPasswordUseCase(sl<AuthRepository>()))
    // ── Blocs ─────────────────────────────────────────────────────────────
    ..registerFactory<AuthBloc>(
      () => AuthBloc(
        loginUseCase: sl<LoginUseCase>(),
        logoutUseCase: sl<LogoutUseCase>(),
        forgotPasswordUseCase: sl<ForgotPasswordUseCase>(),
        registerUseCase: sl<RegisterUseCase>(),
        repository: sl<AuthRepository>(),
      ),
    );
}
